# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _BMCSimulator
else:
    import _BMCSimulator

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _BMCSimulator.delete_SwigPyIterator

    def value(self):
        return _BMCSimulator.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _BMCSimulator.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _BMCSimulator.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _BMCSimulator.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _BMCSimulator.SwigPyIterator_equal(self, x)

    def copy(self):
        return _BMCSimulator.SwigPyIterator_copy(self)

    def next(self):
        return _BMCSimulator.SwigPyIterator_next(self)

    def __next__(self):
        return _BMCSimulator.SwigPyIterator___next__(self)

    def previous(self):
        return _BMCSimulator.SwigPyIterator_previous(self)

    def advance(self, n):
        return _BMCSimulator.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _BMCSimulator.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _BMCSimulator.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _BMCSimulator.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _BMCSimulator.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _BMCSimulator.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _BMCSimulator.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _BMCSimulator:
_BMCSimulator.SwigPyIterator_swigregister(SwigPyIterator)

class vectorMatrixXd(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _BMCSimulator.vectorMatrixXd_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _BMCSimulator.vectorMatrixXd___nonzero__(self)

    def __bool__(self):
        return _BMCSimulator.vectorMatrixXd___bool__(self)

    def __len__(self):
        return _BMCSimulator.vectorMatrixXd___len__(self)

    def __getslice__(self, i, j):
        return _BMCSimulator.vectorMatrixXd___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _BMCSimulator.vectorMatrixXd___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _BMCSimulator.vectorMatrixXd___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _BMCSimulator.vectorMatrixXd___delitem__(self, *args)

    def __getitem__(self, *args):
        return _BMCSimulator.vectorMatrixXd___getitem__(self, *args)

    def __setitem__(self, *args):
        return _BMCSimulator.vectorMatrixXd___setitem__(self, *args)

    def pop(self):
        return _BMCSimulator.vectorMatrixXd_pop(self)

    def append(self, x):
        return _BMCSimulator.vectorMatrixXd_append(self, x)

    def empty(self):
        return _BMCSimulator.vectorMatrixXd_empty(self)

    def size(self):
        return _BMCSimulator.vectorMatrixXd_size(self)

    def swap(self, v):
        return _BMCSimulator.vectorMatrixXd_swap(self, v)

    def begin(self):
        return _BMCSimulator.vectorMatrixXd_begin(self)

    def end(self):
        return _BMCSimulator.vectorMatrixXd_end(self)

    def rbegin(self):
        return _BMCSimulator.vectorMatrixXd_rbegin(self)

    def rend(self):
        return _BMCSimulator.vectorMatrixXd_rend(self)

    def clear(self):
        return _BMCSimulator.vectorMatrixXd_clear(self)

    def get_allocator(self):
        return _BMCSimulator.vectorMatrixXd_get_allocator(self)

    def pop_back(self):
        return _BMCSimulator.vectorMatrixXd_pop_back(self)

    def erase(self, *args):
        return _BMCSimulator.vectorMatrixXd_erase(self, *args)

    def __init__(self, *args):
        _BMCSimulator.vectorMatrixXd_swiginit(self, _BMCSimulator.new_vectorMatrixXd(*args))

    def push_back(self, x):
        return _BMCSimulator.vectorMatrixXd_push_back(self, x)

    def front(self):
        return _BMCSimulator.vectorMatrixXd_front(self)

    def back(self):
        return _BMCSimulator.vectorMatrixXd_back(self)

    def assign(self, n, x):
        return _BMCSimulator.vectorMatrixXd_assign(self, n, x)

    def resize(self, *args):
        return _BMCSimulator.vectorMatrixXd_resize(self, *args)

    def insert(self, *args):
        return _BMCSimulator.vectorMatrixXd_insert(self, *args)

    def reserve(self, n):
        return _BMCSimulator.vectorMatrixXd_reserve(self, n)

    def capacity(self):
        return _BMCSimulator.vectorMatrixXd_capacity(self)
    __swig_destroy__ = _BMCSimulator.delete_vectorMatrixXd

# Register vectorMatrixXd in _BMCSimulator:
_BMCSimulator.vectorMatrixXd_swigregister(vectorMatrixXd)

class vectorVectorXd(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _BMCSimulator.vectorVectorXd_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _BMCSimulator.vectorVectorXd___nonzero__(self)

    def __bool__(self):
        return _BMCSimulator.vectorVectorXd___bool__(self)

    def __len__(self):
        return _BMCSimulator.vectorVectorXd___len__(self)

    def __getslice__(self, i, j):
        return _BMCSimulator.vectorVectorXd___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _BMCSimulator.vectorVectorXd___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _BMCSimulator.vectorVectorXd___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _BMCSimulator.vectorVectorXd___delitem__(self, *args)

    def __getitem__(self, *args):
        return _BMCSimulator.vectorVectorXd___getitem__(self, *args)

    def __setitem__(self, *args):
        return _BMCSimulator.vectorVectorXd___setitem__(self, *args)

    def pop(self):
        return _BMCSimulator.vectorVectorXd_pop(self)

    def append(self, x):
        return _BMCSimulator.vectorVectorXd_append(self, x)

    def empty(self):
        return _BMCSimulator.vectorVectorXd_empty(self)

    def size(self):
        return _BMCSimulator.vectorVectorXd_size(self)

    def swap(self, v):
        return _BMCSimulator.vectorVectorXd_swap(self, v)

    def begin(self):
        return _BMCSimulator.vectorVectorXd_begin(self)

    def end(self):
        return _BMCSimulator.vectorVectorXd_end(self)

    def rbegin(self):
        return _BMCSimulator.vectorVectorXd_rbegin(self)

    def rend(self):
        return _BMCSimulator.vectorVectorXd_rend(self)

    def clear(self):
        return _BMCSimulator.vectorVectorXd_clear(self)

    def get_allocator(self):
        return _BMCSimulator.vectorVectorXd_get_allocator(self)

    def pop_back(self):
        return _BMCSimulator.vectorVectorXd_pop_back(self)

    def erase(self, *args):
        return _BMCSimulator.vectorVectorXd_erase(self, *args)

    def __init__(self, *args):
        _BMCSimulator.vectorVectorXd_swiginit(self, _BMCSimulator.new_vectorVectorXd(*args))

    def push_back(self, x):
        return _BMCSimulator.vectorVectorXd_push_back(self, x)

    def front(self):
        return _BMCSimulator.vectorVectorXd_front(self)

    def back(self):
        return _BMCSimulator.vectorVectorXd_back(self)

    def assign(self, n, x):
        return _BMCSimulator.vectorVectorXd_assign(self, n, x)

    def resize(self, *args):
        return _BMCSimulator.vectorVectorXd_resize(self, *args)

    def insert(self, *args):
        return _BMCSimulator.vectorVectorXd_insert(self, *args)

    def reserve(self, n):
        return _BMCSimulator.vectorVectorXd_reserve(self, n)

    def capacity(self):
        return _BMCSimulator.vectorVectorXd_capacity(self)
    __swig_destroy__ = _BMCSimulator.delete_vectorVectorXd

# Register vectorVectorXd in _BMCSimulator:
_BMCSimulator.vectorVectorXd_swigregister(vectorVectorXd)

M_PI = _BMCSimulator.M_PI
class Scanner(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    B0 = property(_BMCSimulator.Scanner_B0_get, _BMCSimulator.Scanner_B0_set)
    relB1 = property(_BMCSimulator.Scanner_relB1_get, _BMCSimulator.Scanner_relB1_set)
    B0Inhomogeneity = property(_BMCSimulator.Scanner_B0Inhomogeneity_get, _BMCSimulator.Scanner_B0Inhomogeneity_set)
    Gamma = property(_BMCSimulator.Scanner_Gamma_get, _BMCSimulator.Scanner_Gamma_set)

    def __init__(self):
        _BMCSimulator.Scanner_swiginit(self, _BMCSimulator.new_Scanner())
    __swig_destroy__ = _BMCSimulator.delete_Scanner

# Register Scanner in _BMCSimulator:
_BMCSimulator.Scanner_swigregister(Scanner)

SuperLorentzian = _BMCSimulator.SuperLorentzian
Lorentzian = _BMCSimulator.Lorentzian
NoLineshape = _BMCSimulator.NoLineshape
class WaterPool(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _BMCSimulator.WaterPool_swiginit(self, _BMCSimulator.new_WaterPool(*args))
    __swig_destroy__ = _BMCSimulator.delete_WaterPool

    def GetR1(self):
        return _BMCSimulator.WaterPool_GetR1(self)

    def GetR2(self):
        return _BMCSimulator.WaterPool_GetR2(self)

    def GetFraction(self):
        return _BMCSimulator.WaterPool_GetFraction(self)

    def SetR1(self, nR1):
        return _BMCSimulator.WaterPool_SetR1(self, nR1)

    def SetR2(self, nR2):
        return _BMCSimulator.WaterPool_SetR2(self, nR2)

    def SetFraction(self, nf):
        return _BMCSimulator.WaterPool_SetFraction(self, nf)

# Register WaterPool in _BMCSimulator:
_BMCSimulator.WaterPool_swigregister(WaterPool)

class CESTPool(WaterPool):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _BMCSimulator.CESTPool_swiginit(self, _BMCSimulator.new_CESTPool(*args))
    __swig_destroy__ = _BMCSimulator.delete_CESTPool

    def GetShiftinPPM(self):
        return _BMCSimulator.CESTPool_GetShiftinPPM(self)

    def GetExchangeRateInHz(self):
        return _BMCSimulator.CESTPool_GetExchangeRateInHz(self)

    def SetShiftinPPM(self, ndw):
        return _BMCSimulator.CESTPool_SetShiftinPPM(self, ndw)

    def SetExchangeRateInHz(self, nk):
        return _BMCSimulator.CESTPool_SetExchangeRateInHz(self, nk)

# Register CESTPool in _BMCSimulator:
_BMCSimulator.CESTPool_swigregister(CESTPool)

class MTPool(CESTPool):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _BMCSimulator.MTPool_swiginit(self, _BMCSimulator.new_MTPool(*args))
    __swig_destroy__ = _BMCSimulator.delete_MTPool

    def GetMTLineShape(self):
        return _BMCSimulator.MTPool_GetMTLineShape(self)

    def SetMTLineShape(self, nls):
        return _BMCSimulator.MTPool_SetMTLineShape(self, nls)

    def GetMTLineAtCurrentOffset(self, offset, omega0):
        return _BMCSimulator.MTPool_GetMTLineAtCurrentOffset(self, offset, omega0)

# Register MTPool in _BMCSimulator:
_BMCSimulator.MTPool_swigregister(MTPool)

class SimulationParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _BMCSimulator.SimulationParameters_swiginit(self, _BMCSimulator.new_SimulationParameters())
    __swig_destroy__ = _BMCSimulator.delete_SimulationParameters

    def SetInitialMagnetizationVector(self, MagVec):
        return _BMCSimulator.SimulationParameters_SetInitialMagnetizationVector(self, MagVec)

    def GetInitialMagnetizationVector(self):
        return _BMCSimulator.SimulationParameters_GetInitialMagnetizationVector(self)

    def SetWaterPool(self, waterPool):
        return _BMCSimulator.SimulationParameters_SetWaterPool(self, waterPool)

    def GetWaterPool(self):
        return _BMCSimulator.SimulationParameters_GetWaterPool(self)

    def SetCESTPool(self, cp, poolIdx):
        return _BMCSimulator.SimulationParameters_SetCESTPool(self, cp, poolIdx)

    def GetCESTPool(self, poolIdx):
        return _BMCSimulator.SimulationParameters_GetCESTPool(self, poolIdx)

    def SetMTPool(self, cp):
        return _BMCSimulator.SimulationParameters_SetMTPool(self, cp)

    def GetMTPool(self):
        return _BMCSimulator.SimulationParameters_GetMTPool(self)

    def InitScanner(self, *args):
        return _BMCSimulator.SimulationParameters_InitScanner(self, *args)

    def GetScannerB0(self):
        return _BMCSimulator.SimulationParameters_GetScannerB0(self)

    def GetScannerRelB1(self):
        return _BMCSimulator.SimulationParameters_GetScannerRelB1(self)

    def GetScannerB0Inhom(self):
        return _BMCSimulator.SimulationParameters_GetScannerB0Inhom(self)

    def GetScannerGamma(self):
        return _BMCSimulator.SimulationParameters_GetScannerGamma(self)

    def SetScannerRelB1(self, rb1):
        return _BMCSimulator.SimulationParameters_SetScannerRelB1(self, rb1)

    def SetScannerB0Inhom(self, db0):
        return _BMCSimulator.SimulationParameters_SetScannerB0Inhom(self, db0)

    def IsMTActive(self):
        return _BMCSimulator.SimulationParameters_IsMTActive(self)

    def SetNumberOfCESTPools(self, nPools):
        return _BMCSimulator.SimulationParameters_SetNumberOfCESTPools(self, nPools)

    def GetNumberOfCESTPools(self):
        return _BMCSimulator.SimulationParameters_GetNumberOfCESTPools(self)

    def SetVerbose(self, v):
        return _BMCSimulator.SimulationParameters_SetVerbose(self, v)

    def IsVerbose(self):
        return _BMCSimulator.SimulationParameters_IsVerbose(self)

    def SetUseInitMagnetization(self, initMag):
        return _BMCSimulator.SimulationParameters_SetUseInitMagnetization(self, initMag)

    def GetUseInitMagnetization(self):
        return _BMCSimulator.SimulationParameters_GetUseInitMagnetization(self)

    def SetMaxNumberOfPulseSamples(self, numSamples):
        return _BMCSimulator.SimulationParameters_SetMaxNumberOfPulseSamples(self, numSamples)

    def GetMaxNumberOfPulseSamples(self):
        return _BMCSimulator.SimulationParameters_GetMaxNumberOfPulseSamples(self)

# Register SimulationParameters in _BMCSimulator:
_BMCSimulator.SimulationParameters_swigregister(SimulationParameters)

MAX_CEST_POOLS = _BMCSimulator.MAX_CEST_POOLS
class BMCSimulator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, arg2, arg3):
        _BMCSimulator.BMCSimulator_swiginit(self, _BMCSimulator.new_BMCSimulator(arg2, arg3))

    def RunSimulation(self):
        return _BMCSimulator.BMCSimulator_RunSimulation(self)
    __swig_destroy__ = _BMCSimulator.delete_BMCSimulator

# Register BMCSimulator in _BMCSimulator:
_BMCSimulator.BMCSimulator_swigregister(BMCSimulator)



